#!/usr/bin/env node

require("module-alias/register")
const { run, test, expect, snapshot, info } = require("@xieyuheng/test-runner")
const changeCase = require("change-case")
const path = require("path")
const fs = require("fs")

let commands = {}

commands.t = async () => {
  await commands.test_all()
}

commands.test_all = async () => {
  await commands.test_lib()
  await commands.test_impression()
  await commands.test_cicada()
}

commands.test_lib = async () => {
  await test("node $file", { file: "lib/**/*.test.js" }, expect.ok)
}

commands.test_impression = async () => {
  await test(
    "node $file",
    { file: "lib/**/*.impression.js" },
    snapshot.out(({ file }) =>
      path.resolve("snapshot", changeCase.paramCase(file) + ".out")
    )
  )
}

commands.test_cicada = async () => {
  await test("./bin/cic.js $file", { file: "tests/**/**.test.cic" }, expect.ok)

  await test(
    "./bin/cic.js $file",
    { file: "tests/**/**.snapshot.cic" },
    snapshot.out(({ file }) => file.replace(/\.cic$/, ".out"))
  )
}

info()

run(commands)
