#!/usr/bin/env node

const run = require("./scripts/run")
const snapshot = require("./scripts/snapshot")

let dev = {}

dev.lib = () => snapshot.out("node", "lib/**.test.js")
dev.lang0_out = () => snapshot.out("./bin/lang0.js eval", "tests/lang0/**.cic")
dev.lang1_out = () => snapshot.out("./bin/lang1.js eval", "tests/lang1/**.cic")
dev.lang1_err = () => snapshot.err("./bin/lang1.js eval", "tests/lang1-error/**.cic")
dev.lang2_out = () => snapshot.out("./bin/lang2.js eval", "tests/lang2/**.cic")
dev.lang2_err = () => snapshot.err("./bin/lang2.js eval", "tests/lang2-error/**.cic")

dev.t = () => {
  dev.lib()
  dev.lang0_out()
  dev.lang1_out()
  dev.lang1_err()
  dev.lang2_err()
  dev.lang2_err()
}

run(dev)
