#!/usr/bin/env bash

npx plaintext toc tests -o test/toc --verbose
npx plaintext dir tests -o out/tests --verbose

npx plaintext toc docs -o docs/toc --verbose
cat docs/README.txt <(echo) docs/toc > docs/index
npx plaintext dir docs -o out --verbose
