#!/usr/bin/env bash

plaintext toc docs -o docs/toc --verbose
plaintext dir docs -o out/docs --verbose
plaintext toc cicada -o cicada/toc --verbose
plaintext dir cicada -o out/cicada --verbose


        npx plaintext toc src -o src/toc &&
        cat README.txt <(echo) docs/toc > src/index &&
        npx plaintext dir src -o out &&
