export * from "./evaluate"
export * from "./evaluate-do-ap"
export * from "./evaluate-do-car"
export * from "./evaluate-do-cdr"
export * from "./evaluate-do-nat-ind"
export * from "./evaluate-do-absurd-ind"
export * from "./evaluate-do-replace"
