export * from "./var"
export * from "./fn"
export * from "./ap"
export * from "./zero"
export * from "./add1"
export * from "./rec"
export * from "./begin"
export * from "./the"

export * from "./arrow-ty"
export * from "./nat-ty"

export * from "./fn-value"
export * from "./zero-value"
export * from "./add1-value"
export * from "./not-yet-value"

export * from "./var-neutral"
// export * from "./ap-neutral"
// export * from "./rec-neutral"
