export * from "./var"
export * from "./fn"
export * from "./ap"
export * from "./zero"
export * from "./add1"
export * from "./rec"
export * from "./begin"
export * from "./the"

export * from "./arrow"
export * from "./nat"
